const placeDic = {
  accomcount: "수용 인원",
  chkbabycarriage: "유모차 대여",
  chkcreditcard: "신용카드",
  chkpet: "애완동물 동반",
  expagerange: "체험가능 연령",
  expguide: "체험안내",
  heritage1: "세계문화유산",
  heritage2: "세계자연유산",
  heritage3: "세계기록유산",
  infocenter: "문의 및 안내",
  opendate: "개장일",
  parking: "주차시설",
  restdate: "쉬는 날",
  useseason: "이용시기",
  usetime: "이용시간",
  accomcountculture: "수용인원",
  chkbabycarriageculture: "유모차 대여",
  chkcreditcardculture: "신용카드",
  chkpetculture: "애완동물 동반",
  discountinfo: "할인정보",
  infocenterculture: "문의 및 안내",
  parkingculture: "주차 시설",
  parkingfee: "주차 요금",
  restdateculture: "쉬는 날",
  usefee: "이용요금",
  usetimeculture: "이용시간",
  scale: "규모",
  spendtime: "관람 소요 시간",
  distance: "코스 총거리",
  infocentertourcourse: "문의 및 안내",
  schedule: "코스 일정",
  taketime: "코스 총 소요시간",
  theme: "코스 테마",
  accomcountleports: "수용 인원",
  chkbabycarriageleports: "유모차 대여",
  chkcreditcardleports: "신용카드",
  chkpetleports: "애완동물 동반",
  expagerangeleports: "체험가능 연령",
  infocenterleports: "문의 및 안내",
  openperiod: "개장기간",
  parkingfeeleports: "주차요금",
  parkingleports: "주차시설",
  reservation: "예약안내",
  restdateleports: "쉬는 날",
  scaleleports: "규모",
  usefeeleports: "입장료",
  usetimeleports: "이용시간",
  accomcountlodging: "수용가능인원",
  benikia: "베니키아",
  checkintime: "입실시간",
  checkouttime: "퇴실시간",
  chkcooking: "객실 내 취사",
  foodplace: "식음료장",
  goodstay: "굿스테이",
  hanok: "한옥여부",
  infocenterlodging: "문의 및 안내",
  parkinglodging: "주차시설",
  pickup: "픽업서비스",
  roomcount: "객실 수",
  reservationlodging: "예약안내",
  reservationurl: "예약안내 홈페이지",
  roomtype: "객실유형",
  scalelodging: "규모",
  subfacility: "부대시설 (기타)",
  barbecue: "바비큐장",
  beauty: "뷰티시설",
  beverage: "식음료장",
  bicycle: "자전거 대여",
  campfire: "캠프파이어",
  fitness: "휘트니스 센터",
  karaoke: "노래방",
  publicbath: "공용 샤워실",
  publicpc: "공용 PC실여부",
  sauna: "사우나실",
  seminar: "세미나실",
  sports: "스포츠 시설",
  refundregulation: "환불규정",
  chkbabycarriageshopping: "유모차 대여",
  chkcreditcardshopping: "신용카드",
  chkpetshopping: "애완동물 동반",
  culturecenter: "문화센터 바로가기",
  fairday: "장 서는 날",
  infocentershopping: "문의 및 안내",
  opendateshopping: "개장일",
  opentime: "영업시간",
  parkingshopping: "주차시설",
  restdateshopping: "쉬는 날",
  restroom: "화장실",
  saleitem: "판매품목",
  saleitemcost: "판매품목별 가격",
  scaleshopping: "규모",
  shopguide: "매장안내",
  chkcreditcardfood: "신용카드",
  discountinfofood: "할인",
  firstmenu: "대표 메뉴",
  infocenterfood: "문의 및 안내",
  kidsfacility: "어린이 놀이방",
  opendatefood: "개업 일",
  opentimefood: "영업시간",
  packing: "포장가능",
  parkingfood: "주차시설",
  reservationfood: "예약 안내",
  restdatefood: "쉬는날",
  scalefood: "규모",
  seat: "좌석 수",
  smoking: "금연/흡연",
  treatmenu: "취급 메뉴",
  lcnsno: "인허가 번호"
};

export default placeDic;
